# Generated by Django 4.1.6 on 2023-04-17 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Field', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('semester', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], default='1', max_length=2)),
                ('question_num', models.IntegerField()),
                ('question_subnum', models.IntegerField()),
                ('question', models.TextField()),
                ('question_ans', models.TextField()),
                ('question_ans_img', models.ImageField(blank=True, upload_to='./static/image/paperimage/')),
            ],
        ),
    ]
