# Generated by Django 4.2 on 2023-04-21 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_paper_exam_type_paper_year_alter_paper_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='subject',
            field=models.CharField(default='None', max_length=20),
        ),
        migrations.AlterField(
            model_name='paper',
            name='exam_type',
            field=models.CharField(choices=[('End Sem', 'End Sem'), ('Mid Sem', 'Mid Sem'), ('Remid', 'Remid'), ('Backlog', 'Backlog')], default='End Sem', max_length=20),
        ),
        migrations.AlterField(
            model_name='paper',
            name='semester',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='paper',
            name='year',
            field=models.IntegerField(choices=[(2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023)], default='2023', verbose_name='year'),
        ),
    ]
